# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [5]:
# Create our features
X = df.drop(columns=["loan_status"], axis=1)

# Create our target
y = df['loan_status']
y

0        low_risk
1        low_risk
2        low_risk
3        low_risk
4        low_risk
           ...
68812    low_risk
68813    low_risk
68814    low_risk
68815    low_risk
68816    low_risk
Name: loan_status, Length: 68817, dtype: object

In [6]:
X.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,dti,delinq_2yrs,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,n,27.24,0.0,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,n,20.23,0.0,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,n,24.26,0.0,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,n,31.44,0.0,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,n,18.76,0.0,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [7]:
# Check the balance of our target values
df[["loan_status"]].value_counts()

loan_status
low_risk       68470
high_risk        347
dtype: int64

In [8]:
X.columns

Index(['loan_amnt', 'int_rate', 'installment', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'pymnt_plan', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'next_pymnt_d', 'collections_12_mths_ex_med',
       'policy_code', 'application_type', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_act_il', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'debt_settlement_flag'],
      dtype='object')

In [9]:
X_bin = pd.get_dummies(X, columns=["home_ownership", "verification_status", "issue_d", "pymnt_plan", "initial_list_status", "next_pymnt_d", "application_type", "hardship_flag", "debt_settlement_flag"])

X_bin.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [10]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_bin,
                                                    y,
                                                    random_state=1)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [11]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [12]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
X_scaler = scaler.fit(X_train)

In [13]:
# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)

X_test_scaled = X_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [14]:
# Resample the training data with the BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=500,
                                  random_state=42)


rf_model.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=500, random_state=42)

In [15]:
# Calculated the balanced accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

rf_pred = rf_model.predict(X_test_scaled)

rf_acc_score = accuracy_score(y_test, rf_pred)

print(f"The accuracy score for the Balanced Random Forest Classifier is {rf_acc_score}.")

The accuracy score for the Balanced Random Forest Classifier is 0.9960476605637896.

In [16]:
# Display the confusion matrix
rf_cm = confusion_matrix(y_test, rf_pred)

rf_cm_df = pd.DataFrame(rf_cm,
                        index=["Actual False", "Actual True"],
                        columns=["Predicted False", "Predicted True"])

rf_cm_df

              Predicted False  Predicted True
Actual False               37              64
Actual True                 4           17100

In [17]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, rf_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.90      0.37      1.00      0.52      0.61      0.34       101
   low_risk       1.00      1.00      0.37      1.00      0.61      0.39     17104

avg / total       1.00      1.00      0.37      1.00      0.61      0.39     17205

In [18]:
# List the features sorted in descending order by feature importance
rf_importances = rf_model.feature_importances_

sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.0704577614774606, 'out_prncp'),
 (0.06851571074119261, 'total_acc'),
 (0.06678684949959895, 'total_rec_prncp'),
 (0.059975960224828366, 'initial_list_status'),
 (0.05985277832212354, 'revol_bal'),
 (0.021954993704883744, 'installment'),
 (0.019889661422775016, 'pub_rec'),
 (0.019532515583778935, 'open_acc'),
 (0.016561999715022084, 'acc_open_past_24mths'),
 (0.016287965893022595, 'annual_inc'),
 (0.016109567140325406, 'open_il_12m'),
 (0.015354160817770444, 'inq_last_12m'),
 (0.015110705040483816, 'loan_amnt'),
 (0.015058257081250668, 'delinq_2yrs'),
 (0.01459027319094609, 'all_util'),
 (0.014039682030988047, 'max_bal_bc'),
 (0.01403322788132459, 'num_tl_30dpd'),
 (0.01403092409313799, 'last_pymnt_amnt'),
 (0.01391375341982648, 'num_tl_90g_dpd_24m'),
 (0.013792553383010163, 'tot_coll_amt'),
 (0.013605329463640292, 'total_rev_hi_lim'),
 (0.013065970993287625, 'home_ownership'),
 (0.012639077725431965, 'tot_cur_bal'),
 (0.012623401365315689, 'pct_tl_nvr_dlq'),
 (0.012594603392861226, 'mths_since_rcnt_il'),
 (0.012548171757668487, 'num_tl_op_past_12m'),
 (0.01248296977263828, 'out_prncp_inv'),
 (0.01202375130187115, 'acc_now_delinq'),
 (0.01200181470487668, 'int_rate'),
 (0.011586817692588432, 'inq_last_6mths'),
 (0.011557907814846577, 'open_il_24m'),
 (0.011363509555425234, 'mths_since_recent_bc'),
 (0.011004513949995265, 'chargeoff_within_12_mths'),
 (0.010358380484839315, 'num_accts_ever_120_pd'),
 (0.010123014274900095, 'delinq_amnt'),
 (0.009334874064206796, 'open_rv_24m'),
 (0.009075275240176942, 'avg_cur_bal'),
 (0.008740381483239534, 'num_rev_accts'),
 (0.008532836205272534, 'bc_open_to_buy'),
 (0.00839995685574295, 'il_util'),
 (0.008307396768461848, 'open_rv_12m'),
 (0.00821521263063408, 'pymnt_plan'),
 (0.008146738190993298, 'mort_acc'),
 (0.007989243427962677, 'mo_sin_rcnt_rev_tl_op'),
 (0.007815983128935349, 'open_act_il'),
 (0.007806627511040862, 'num_actv_rev_tl'),
 (0.007694544324012736, 'mths_since_recent_inq'),
 (0.007567010517477828, 'num_actv_bc_tl'),
 (0.007418383452443836, 'mo_sin_rcnt_tl'),
 (0.007341131762563053, 'application_type'),
 (0.00723535971072499, 'mo_sin_old_rev_tl_op'),
 (0.0071555571692287784, 'num_rev_tl_bal_gt_0'),
 (0.006847714600825462, 'total_bal_il'),
 (0.006844311343146622, 'num_op_rev_tl'),
 (0.006560033681662888, 'bc_util'),
 (0.006380391231913759, 'collections_12_mths_ex_med'),
 (0.00634831487596453, 'next_pymnt_d'),
 (0.005625982471064462, 'hardship_flag'),
 (0.005137245021900987, 'open_acc_6m'),
 (0.005077937317568265, 'collection_recovery_fee'),
 (0.0049136586629680125, 'debt_settlement_flag'),
 (0.004819874119795376, 'issue_d'),
 (0.004092158468632487, 'policy_code'),
 (0.003561363825119666, 'mo_sin_old_il_acct'),
 (0.0032446725627799412, 'verification_status'),
 (0.002731311099324949, 'dti'),
 (0.0026849449401890853, 'num_sats'),
 (0.0021782403713916415, 'total_bal_ex_mort'),
 (0.0020515910665905874, 'total_bc_limit'),
 (0.0019753156131503496, 'total_il_high_credit_limit'),
 (0.0018631742751677768, 'tax_liens'),
 (0.0017980379423342616, 'total_rec_int'),
 (0.0017948530385858263, 'tot_hi_cred_lim'),
 (0.0017572630589713855, 'pub_rec_bankruptcies'),
 (0.0015196962834041726, 'num_il_tl'),
 (0.0006626024857330802, 'percent_bc_gt_75'),
 (0.0003321905717699401, 'inq_fi'),
 (0.0, 'total_rec_late_fee'),
 (0.0, 'total_pymnt_inv'),
 (0.0, 'total_pymnt'),
 (0.0, 'total_cu_tl'),
 (0.0, 'recoveries'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'num_bc_tl'),
 (0.0, 'num_bc_sats')]

### Easy Ensemble Classifier

In [19]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier

easy_ens = EasyEnsembleClassifier(n_estimators=10,
                                  random_state=1)

easy_ens.fit(X_train_scaled, y_train)

EasyEnsembleClassifier(random_state=1)

In [20]:
# Calculated the balanced accuracy score
easy_ens_pred = easy_ens.predict(X_test_scaled)

from sklearn.metrics import balanced_accuracy_score
easy_ens_bal_acc_score = balanced_accuracy_score(y_test, easy_ens_pred)

print(f"The balanced accuracy score for the Easy Ensemble Classifier is {easy_ens_bal_acc_score}")

The balanced accuracy score for the Easy Ensemble Classifier is 0.9154459266085636

In [21]:
# Display the confusion matrix
easy_ens_cm = confusion_matrix(y_test, easy_ens_pred)

easy_ens_cm_df = pd.DataFrame(easy_ens_cm,
                              index=["Actual False", "Actual True"],
                              columns=["Predicted False", "Predicted True"])

easy_ens_cm_df

              Predicted False  Predicted True
Actual False               94               7
Actual True              1707           15397

In [22]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, easy_ens_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.05      0.93      0.90      0.10      0.92      0.84       101
   low_risk       1.00      0.90      0.93      0.95      0.92      0.84     17104

avg / total       0.99      0.90      0.93      0.94      0.92      0.84     17205

### Final Questions

1. Which model had the best balanced accuracy score?

The Balanced Random Forest Classifier model resulted in a accurate balanced score (0.9960476605637896.) when compared to the Easy Ensemble Classifier (0.9154459266085636) model. 

2. Which model had the best recall score?

The Easy Ensemble Classifier model resulted in a better recall score (high risk: 0.93 & low risk: 0.90) when compared to the Balanced Random Forest Classifier (high risk: 0.37 & low risk: 1) model.

3. Which model had the best geometric mean score?

The Easy Ensemble Classifier model has a precise geometric score (high risk: 0.92 & low risk: 0.92) when compared to the Balanced Random Forest Classifier (high risk: 0.34 & low risk: 0.39) model.

4. What are the top three features?

The top 3 features for the Balanced Random Forest Classifier model are: i) out_prncp ii) total_acc, and iii) total_rec_prncp.